export const types = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_FAILED',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    RESGISTER_SUCCESS: 'RESGISTER_SUCCESS',
    RESGISTER_FAILED: 'RESGISTER_FAILED',

    GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',

    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_ID_SUCCESS: 'GET_PRODUCT_ID_SUCCESS',
    GET_PRODUCT_CATEGORY_SUCCESS: 'GET_PRODUCT_CATEGORY_SUCCESS',

    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT'
}